[package]
name = "singularity"
version = "0.1.0"
edition = "2021"

[features]
default = ["bevy/bevy_gltf", "bevy/png", "bevy/render", "bevy/bevy_winit"]
native = ["bevy/dynamic"]
debug = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.6.1", default-features = false }
bevy_rapier3d = "0.12.1"
bevy-inspector-egui = { version = "0.9", optional = true }
