[package]
name = "singularity"
version = "0.1.0"
edition = "2021"

[features]
default = ["bevy/bevy_gltf", "bevy/bevy_winit", "bevy/render", "bevy/png"]
debug = ["bevy-inspector-egui"]
native = ["bevy/bevy_wgpu", "bevy/dynamic"]
web = ["bevy_webgl2"]

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_rapier3d = "0.11"
bevy_webgl2 = { version = "0.5", optional = true }
bevy-inspector-egui = { version = "0.6", optional = true }
