[package]
name = "singularity"
version = "0.1.0"
edition = "2021"

[features]
debug = ["bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.6.1", features = [
    "bevy_gltf",
    "png",
    "render",
    "bevy_winit",
    "dynamic",
] }
bevy_rapier3d = "0.12.1"
bevy-inspector-egui = { version = "0.9", optional = true }
