[env.release]
RELEASE_ARGS = "-Z unstable-options --out-dir target/bin --release"

[tasks.native]
command = "cargo"
args = ["build", "--features", "native", "@@split(RELEASE_ARGS, )"]

[tasks.prepare-web-target]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.prepare-web-cli]
install_crate = { crate_name = "wasm-bindgen-cli", version = "0.2.69", binary = "wasm-bindgen", test_arg = "--help" }

[tasks.prepare-web]
command = "cargo"
args = [
    "build",
    "--features",
    "web",
    "--target",
    "wasm32-unknown-unknown",
    "--release",
]
dependencies = ["prepare-web-target", "prepare-web-cli"]

[tasks.web]
command = "wasm-bindgen"
args = [
    "--out-dir",
    "target/bin",
    "--out-name",
    "${CARGO_MAKE_CRATE_NAME}",
    "--target",
    "web",
    "--no-typescript",
    "target/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm",
]
dependencies = ["prepare-web"]
