[tasks.native]
script = "cargo build --release"

[tasks.prepare-web-target]
script = "rustup target install wasm32-unknown-unknown"

[tasks.prepare-web-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg = "--help" }

[tasks.prepare-web]
script = "cargo build --target wasm32-unknown-unknown --release"
dependencies = ["prepare-web-target", "prepare-web-cli"]

[tasks.web]
command = "wasm-bindgen"
args = [
    "--out-dir",
    "target/bin",
    "--out-name",
    "${CARGO_MAKE_CRATE_NAME}",
    "--target",
    "web",
    "--no-typescript",
    "target/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm",
]
dependencies = ["prepare-web"]
