[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y"]

[profile.dev]
debug = 1

[profile.release]
lto = "thin"

[alias]
d = "run --features debug"
wd = "watch -x run --features debug"
m = "make web"
