[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y"]

[profile.dev]
debug = 1

[profile.release]
lto = "thin"

[alias]
n = "run --features native"
nd = "run --features native,debug"
w = "watch -x run --features native"
wd = "watch -x run --features native,debug"
m = "make web"
